project:
  type: website

website:
  title: "Psych Foundations Student Repository"
  back-to-top-navigation: true
  repo-url: https://github.com/rlisinker/PsyF-student-repo
  repo-actions: [source, issue]
  navbar:
    right:
      - text: "Menu"
        menu: 
          - href: index.qmd
            text: About
          - href: conferences.qmd
            text: Conferences
          # - href: journals.qmd
          #   text: Journals/Publications
          # - href: milestones.qmd
          #   text: Milestones

format:
  html:
    theme: solar
    css: styles.css
    toc: true
    
editor: visual

