project:
  type: website

website:
  title: "Psych Foundations Student Repository"
  back-to-top-navigation: true
  navbar:
    right:
      - text: "Menu"
        menu: 
          - href: index.qmd
            text: About
          - href: conferences.qmd
            text: Conferences
          # - href: journals.qmd
          #   text: Journals/Publications
          # - href: milestones.qmd
          #   text: Milestones
          - icon: github
            menu:
              - text: Source Code
                href: github.com/rlisinker/PsyF-student-repo
                target: _blank
              - text: Report a Bug
                href: github.com/rlisinker/PsyF-student-repo/issues
                target: _blank
        

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

